services:
  db:
    image: postgres:15-alpine
    container_name: employee-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: employee_admin
      POSTGRES_PASSWORD: User12345
      POSTGRES_DB: employee_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
